<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archivos' => [parent::class, 'archivos', null],
        "\0".parent::class."\0".'avatar_path' => [parent::class, 'avatar_path', null],
        "\0".parent::class."\0".'data_path' => [parent::class, 'data_path', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'fecha_registro' => [parent::class, 'fecha_registro', null],
        "\0".parent::class."\0".'historials' => [parent::class, 'historials', null],
        "\0".parent::class."\0".'home_path' => [parent::class, 'home_path', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'repositorios' => [parent::class, 'repositorios', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'ultimo_acceso' => [parent::class, 'ultimo_acceso', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'archivos' => [parent::class, 'archivos', null],
        'avatar_path' => [parent::class, 'avatar_path', null],
        'data_path' => [parent::class, 'data_path', null],
        'email' => [parent::class, 'email', null],
        'fecha_registro' => [parent::class, 'fecha_registro', null],
        'historials' => [parent::class, 'historials', null],
        'home_path' => [parent::class, 'home_path', null],
        'id' => [parent::class, 'id', null],
        'password' => [parent::class, 'password', null],
        'repositorios' => [parent::class, 'repositorios', null],
        'role' => [parent::class, 'role', null],
        'ultimo_acceso' => [parent::class, 'ultimo_acceso', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
