<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Archivo extends \App\Entity\Archivo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archivos' => [parent::class, 'archivos', null],
        "\0".parent::class."\0".'filehash' => [parent::class, 'filehash', null],
        "\0".parent::class."\0".'filename' => [parent::class, 'filename', null],
        "\0".parent::class."\0".'filepath' => [parent::class, 'filepath', null],
        "\0".parent::class."\0".'filesize' => [parent::class, 'filesize', null],
        "\0".parent::class."\0".'filetype' => [parent::class, 'filetype', null],
        "\0".parent::class."\0".'historials' => [parent::class, 'historials', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_padre' => [parent::class, 'id_padre', null],
        "\0".parent::class."\0".'repoVersion' => [parent::class, 'repoVersion', null],
        "\0".parent::class."\0".'repo_id' => [parent::class, 'repo_id', null],
        "\0".parent::class."\0".'upload_date' => [parent::class, 'upload_date', null],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null],
        'archivos' => [parent::class, 'archivos', null],
        'filehash' => [parent::class, 'filehash', null],
        'filename' => [parent::class, 'filename', null],
        'filepath' => [parent::class, 'filepath', null],
        'filesize' => [parent::class, 'filesize', null],
        'filetype' => [parent::class, 'filetype', null],
        'historials' => [parent::class, 'historials', null],
        'id' => [parent::class, 'id', null],
        'id_padre' => [parent::class, 'id_padre', null],
        'repoVersion' => [parent::class, 'repoVersion', null],
        'repo_id' => [parent::class, 'repo_id', null],
        'upload_date' => [parent::class, 'upload_date', null],
        'user_id' => [parent::class, 'user_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
