<?php

namespace ContainerXI2PhVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFtpControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FtpController' shared autowired service.
     *
     * @return \App\Controller\FtpController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FtpController.php';

        return $container->services['App\\Controller\\FtpController'] = new \App\Controller\FtpController(($container->privates['App\\Service\\FtpService'] ?? $container->load('getFtpServiceService')));
    }
}
