<?php

namespace ContainerEUPPlxm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFtpServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FtpService' shared autowired service.
     *
     * @return \App\Service\FtpService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FtpService.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem-ftp/FtpAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem-ftp/FtpConnectionOptions.php';

        return $container->privates['App\\Service\\FtpService'] = new \App\Service\FtpService(new \League\Flysystem\Ftp\FtpAdapter(new \League\Flysystem\Ftp\FtpConnectionOptions($container->getEnv('SERVER_IP'), '/', 'captain', 'Nantar01', 21, false, 90, false, true)));
    }
}
