<?php

namespace ContainerIKw2KPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XNZF2wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._XNZF2w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._XNZF2w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FtpController::upload' => ['privates', '.service_locator.PBhHKAN.App\\Controller\\FtpController::upload()', 'getFtpControlleruploadService', true],
            'App\\Controller\\FtpController::download' => ['privates', '.service_locator.zQoFpvM.App\\Controller\\FtpController::download()', 'getFtpControllerdownloadService', true],
            'App\\Controller\\FtpController::createRepo' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\FtpController::createRepo()', 'getFtpControllercreateRepoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::login' => ['privates', '.service_locator.OzEre6h.App\\Controller\\RegistrationController::login()', 'getRegistrationControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FtpController:upload' => ['privates', '.service_locator.PBhHKAN.App\\Controller\\FtpController::upload()', 'getFtpControlleruploadService', true],
            'App\\Controller\\FtpController:download' => ['privates', '.service_locator.zQoFpvM.App\\Controller\\FtpController::download()', 'getFtpControllerdownloadService', true],
            'App\\Controller\\FtpController:createRepo' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\FtpController::createRepo()', 'getFtpControllercreateRepoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:login' => ['privates', '.service_locator.OzEre6h.App\\Controller\\RegistrationController::login()', 'getRegistrationControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\FtpController::upload' => '?',
            'App\\Controller\\FtpController::download' => '?',
            'App\\Controller\\FtpController::createRepo' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\FtpController:upload' => '?',
            'App\\Controller\\FtpController:download' => '?',
            'App\\Controller\\FtpController:createRepo' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:login' => '?',
        ]);
    }
}
