<?php

namespace ContainerIKw2KPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFtpControllerdownloadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zQoFpvM.App\Controller\FtpController::download()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zQoFpvM.App\\Controller\\FtpController::download()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'archivoRepository' => ['privates', 'App\\Repository\\ArchivoRepository', 'getArchivoRepositoryService', true],
        ], [
            'archivoRepository' => 'App\\Repository\\ArchivoRepository',
        ]))->withContext('App\\Controller\\FtpController::download()', $container);
    }
}
