<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUPPlxm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUPPlxm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUPPlxm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUPPlxm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEUPPlxm\App_KernelDevDebugContainer([
    'container.build_hash' => 'EUPPlxm',
    'container.build_id' => '08beba42',
    'container.build_time' => 1745480676,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUPPlxm');
